name: discord updates

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send message through webhook
        uses: fjogeleit/http-request-action@v1.15.2
        with:
          url: ${{DISCORD_WEBHOOK_URL}}
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"content": "skull"}'
